### ISSUE TITLE
configuration file

### ISSUE THREAD

**Issue by usernam3** [usernam3/meta_commit#5]
should exist an opportunity to customize the gem main properties :

- commit message formatter
- adapter to write commit meta information (meta_adapter)
  - git notes (default)
  - elasticsearch

I think the config.yml of this structure

```
meta_commit:
  formatter: plain
  meta_adapter: notes
```

would be intuitive solution

**Comment by usernam3** [comment]
Implemented, but with different config structure in 3b0bda046eb43f8a78e44591001e75c65218fbd2
Now gem will search for `.meta_commit.yml` file in the root of inspected directory. Contents of configuration file expected to be of this structure :
```yaml
commands :
  changelog:
    adapter: file
    formatter: keep_a_changelog
  index:
    adapter: git_notes
  message:
    formatter: commit_message

extensions:
  - extension1
  - extension2
  - extension3
```

Currently gem works only with `extensions` key
